# Generated by Django 3.0.5 on 2020-04-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangtesting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='formulaire_test',
            new_name='formulairetest',
        ),
    ]
